agent1:
  image: agent
  ports: 
    - "6667:6667"
  volumes:
    - ./agent.sh:/bin/agent.sh
  command: agent.sh --dip 192.168.0.117 --dport 7788

service1:
  image: service1
  ports: 
    - "6666:6667"
  links:
    - agent1:agent1
  volumes:
    - ./service1.sh:/bin/service1.sh
  command: service1.sh --dip agent1 --dport 6667
